openapi: 3.0.3
info:
  description: This is api documentations of metricark
  title: Swagger metricark - OpenAPI 3.0
  version: 1.0.6
servers:
  - url: /v3
tags:
  - name: cluster
  - name: k8s
  - name: node
  - name: openstack
  - name: query
  - name: system
  - name: ui
x-tagGroups:
  - name: Prometheus
    tags:
      - cluster
      - k8s
      - node
      - system
      - ui
  - name: Redis
    tags:
      - query
  - name: Openstack
    tags:
      - openstack

paths:
  /v1/build-info:
    get:
      tags:
        - openstack
      summary: Build info
      description: 'Build information.'
      operationId: buildInfo
      parameters:
        - name: projectName
          in: query
          description: Project Name
          required: true
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad Request
  
